/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminPage;
import dataController.*;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author alifn
 */
public class settingsPage extends javax.swing.JFrame {

    /**
     * Creates new form settingsPage
     */
    
    public settingsPage() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuSettingPanel = new javax.swing.JPanel();
        hasilBT = new javax.swing.JButton();
        addUserBT = new javax.swing.JButton();
        logoutBT = new javax.swing.JButton();
        logoSetting = new javax.swing.JLabel();
        editCapilBT = new javax.swing.JButton();
        resetBT = new javax.swing.JButton();
        mainSettingPanel = new javax.swing.JPanel();
        addUserPanel = new javax.swing.JPanel();
        nimLabel = new javax.swing.JLabel();
        tglLabel = new javax.swing.JLabel();
        tglTF = new javax.swing.JTextField();
        nimTF = new javax.swing.JTextField();
        submitBT = new javax.swing.JButton();
        notifLabel = new javax.swing.JLabel();
        hasilPanel = new javax.swing.JPanel();
        Suara1 = new javax.swing.JProgressBar();
        Suara2 = new javax.swing.JProgressBar();
        headerHasil = new javax.swing.JLabel();
        imgCapil2 = new javax.swing.JLabel();
        imgCapil1 = new javax.swing.JLabel();
        totSuara = new javax.swing.JLabel();
        totCP1 = new javax.swing.JLabel();
        totCP2 = new javax.swing.JLabel();
        editCapilPanel = new javax.swing.JPanel();
        labelCP1 = new javax.swing.JLabel();
        labelCP2 = new javax.swing.JLabel();
        nameCP1 = new javax.swing.JTextField();
        nameCP2 = new javax.swing.JTextField();
        sourceCP1 = new javax.swing.JTextField();
        sourceCP2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ketCP1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        ketCP2 = new javax.swing.JTextArea();
        submitCP = new javax.swing.JButton();

        menuSettingPanel.setBackground(new java.awt.Color(51, 51, 255));

        hasilBT.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        hasilBT.setText("Hasil");
        hasilBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilBTActionPerformed(evt);
            }
        });

        addUserBT.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        addUserBT.setText("Tambah User");
        addUserBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserBTActionPerformed(evt);
            }
        });

        logoutBT.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        logoutBT.setText("Logout");
        logoutBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBTActionPerformed(evt);
            }
        });

        logoSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/setting1.png"))); // NOI18N

        editCapilBT.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        editCapilBT.setText("Edit Capil");
        editCapilBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCapilBTActionPerformed(evt);
            }
        });

        resetBT.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        resetBT.setText("Reset");
        resetBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuSettingPanelLayout = new javax.swing.GroupLayout(menuSettingPanel);
        menuSettingPanel.setLayout(menuSettingPanelLayout);
        menuSettingPanelLayout.setHorizontalGroup(
            menuSettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuSettingPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(menuSettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logoSetting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addUserBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hasilBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editCapilBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resetBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        menuSettingPanelLayout.setVerticalGroup(
            menuSettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuSettingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hasilBT)
                .addGap(30, 30, 30)
                .addComponent(addUserBT)
                .addGap(36, 36, 36)
                .addComponent(editCapilBT)
                .addGap(30, 30, 30)
                .addComponent(resetBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(logoutBT)
                .addGap(43, 43, 43))
        );

        mainSettingPanel.setLayout(new java.awt.CardLayout());

        nimLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nimLabel.setText("NIM :");

        tglLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tglLabel.setText("Tanggal Lahir :");

        tglTF.setText("Tanggal Lahir");
        tglTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tglTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tglTFFocusLost(evt);
            }
        });
        tglTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglTFActionPerformed(evt);
            }
        });

        nimTF.setText("NIM");
        nimTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nimTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nimTFFocusLost(evt);
            }
        });

        submitBT.setText("Submit");
        submitBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addUserPanelLayout = new javax.swing.GroupLayout(addUserPanel);
        addUserPanel.setLayout(addUserPanelLayout);
        addUserPanelLayout.setHorizontalGroup(
            addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addUserPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitBT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
            .addGroup(addUserPanelLayout.createSequentialGroup()
                .addGroup(addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addUserPanelLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(addUserPanelLayout.createSequentialGroup()
                                .addComponent(nimLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nimTF, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addUserPanelLayout.createSequentialGroup()
                                .addComponent(tglLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tglTF, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(addUserPanelLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(notifLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        addUserPanelLayout.setVerticalGroup(
            addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addUserPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nimLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nimTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tglLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(submitBT, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notifLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        mainSettingPanel.add(addUserPanel, "card2");

        headerHasil.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        headerHasil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerHasil.setText("Hasil Rekapitulasi Suara");

        imgCapil2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        imgCapil1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        totSuara.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        totSuara.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totSuara.setText("Total Suara : ");

        totCP1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        totCP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totCP1.setText("Suara 1");

        totCP2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        totCP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totCP2.setText("Suara 2");

        javax.swing.GroupLayout hasilPanelLayout = new javax.swing.GroupLayout(hasilPanel);
        hasilPanel.setLayout(hasilPanelLayout);
        hasilPanelLayout.setHorizontalGroup(
            hasilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hasilPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(imgCapil1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(hasilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Suara1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totCP1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(hasilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Suara2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totCP2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imgCapil2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addComponent(headerHasil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
            .addGroup(hasilPanelLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(totSuara, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hasilPanelLayout.setVerticalGroup(
            hasilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hasilPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(hasilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hasilPanelLayout.createSequentialGroup()
                        .addGroup(hasilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgCapil1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imgCapil2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(hasilPanelLayout.createSequentialGroup()
                        .addGroup(hasilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Suara1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Suara2, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
                        .addGap(21, 21, 21)
                        .addGroup(hasilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totCP2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(totCP1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totSuara, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainSettingPanel.add(hasilPanel, "card3");

        labelCP1.setText("Capil 1");

        labelCP2.setText("Capil 2");

        nameCP1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameCP1.setText("Nama");
        nameCP1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameCP1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameCP1FocusLost(evt);
            }
        });

        nameCP2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameCP2.setText("Nama");
        nameCP2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameCP2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameCP2FocusLost(evt);
            }
        });

        sourceCP1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sourceCP1.setText("Source Image(location file)");
        sourceCP1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sourceCP1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                sourceCP1FocusLost(evt);
            }
        });

        sourceCP2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sourceCP2.setText("Source Image(location file)");
        sourceCP2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sourceCP2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                sourceCP2FocusLost(evt);
            }
        });

        ketCP1.setColumns(20);
        ketCP1.setRows(5);
        ketCP1.setText("Keterangan");
        ketCP1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ketCP1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ketCP1FocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(ketCP1);

        ketCP2.setColumns(20);
        ketCP2.setRows(5);
        ketCP2.setText("Keterangan");
        ketCP2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ketCP2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ketCP2FocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(ketCP2);

        submitCP.setText("Submit");
        submitCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitCPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editCapilPanelLayout = new javax.swing.GroupLayout(editCapilPanel);
        editCapilPanel.setLayout(editCapilPanelLayout);
        editCapilPanelLayout.setHorizontalGroup(
            editCapilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editCapilPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(editCapilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(sourceCP1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameCP1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCP1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(editCapilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labelCP2)
                    .addComponent(nameCP2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sourceCP2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
            .addGroup(editCapilPanelLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(submitCP, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        editCapilPanelLayout.setVerticalGroup(
            editCapilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editCapilPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(editCapilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCP1)
                    .addComponent(labelCP2))
                .addGap(28, 28, 28)
                .addGroup(editCapilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameCP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameCP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editCapilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sourceCP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sourceCP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editCapilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submitCP, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        mainSettingPanel.add(editCapilPanel, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 156, Short.MAX_VALUE)
                .addComponent(mainSettingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(menuSettingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 541, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainSettingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(menuSettingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hasilBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilBTActionPerformed
        try {
            // TODO add your handling code here:
            dataCenter data = new dataCenter();
            data.readData();
            if (data.getImgCapil1().charAt(1)=='i' && data.getImgCapil1().charAt(2)=='m' && data.getImgCapil1().charAt(3)=='g'){
                imgCapil1.setIcon(new javax.swing.ImageIcon(((new ImageIcon(getClass().getResource(data.getImgCapil1())).getImage()).getScaledInstance(150, 220, java.awt.Image.SCALE_SMOOTH))));
                imgCapil2.setIcon(new javax.swing.ImageIcon(((new ImageIcon(getClass().getResource(data.getImgCapil2())).getImage()).getScaledInstance(150, 220, java.awt.Image.SCALE_SMOOTH))));
            }else {
                imgCapil1.setIcon(new javax.swing.ImageIcon(((new ImageIcon(data.getImgCapil1())).getImage()).getScaledInstance(150, 220, java.awt.Image.SCALE_SMOOTH)));
                imgCapil2.setIcon(new javax.swing.ImageIcon(((new ImageIcon(data.getImgCapil2())).getImage()).getScaledInstance(150, 220, java.awt.Image.SCALE_SMOOTH)));
            }
            totCP1.setText(""+data.suaraCapil1());
            totCP2.setText(""+data.suaraCapil2());
            Suara1.setVisible(true);
            Suara2.setVisible(true);
            Suara1.setStringPainted(true);
            Suara1.setOrientation(1);
            Suara2.setOrientation(1);
            Suara2.setStringPainted(true);
            Suara1.setMaximum(data.totalSuara());
            Suara2.setMaximum(data.totalSuara());
            Suara1.setValue(data.suaraCapil1());
            Suara2.setValue(data.suaraCapil2());
            totSuara.setText("Total Suara : "+data.totalSuara());
            mainSettingPanel.removeAll();
            mainSettingPanel.repaint();
            mainSettingPanel.revalidate();
            
            mainSettingPanel.add(hasilPanel);
            mainSettingPanel.repaint();
            mainSettingPanel.revalidate();
        } catch (IOException ex) {
            Logger.getLogger(settingsPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_hasilBTActionPerformed

    private void logoutBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBTActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_logoutBTActionPerformed

    private void tglTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglTFActionPerformed

    private void submitBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBTActionPerformed
        try {
            // TODO add your handling code here:
            dataCenter data = new dataCenter();
            data.readData();
            //System.out.println(data.isNull());
            if (data.isNull()){
                data.addUser(nimTF.getText(), tglTF.getText());
                notifLabel.setText("Berhasil Tambah Data");
                tglTF.setText("Tanggal Lahir");
                nimTF.setText("NIM");
                data.writeData();
            }
            for(dataUser a : data.getdataUser()){
                if (a.getNIM().equals(nimTF.getText()) && a.getTglLahir().equals(tglTF.getText())){
                    notifLabel.setText("User Sudah Terdaftar");
                    tglTF.setText("Tanggal Lahir");
                    nimTF.setText("NIM");
                }else if (!a.getNIM().equals(nimTF.getText()) && !a.getTglLahir().equals(tglTF.getText())){
                    data.addUser(nimTF.getText(), tglTF.getText());
                    notifLabel.setText("Berhasil Tambah Data");
                    tglTF.setText("Tanggal Lahir");
                    nimTF.setText("NIM");
                    data.writeData();
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(settingsPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submitBTActionPerformed

    private void nimTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nimTFFocusLost
        // TODO add your handling code here:
        if (nimTF.getText().equals("")){
            nimTF.setText("NIM");
            notifLabel.setText("");
        }
    }//GEN-LAST:event_nimTFFocusLost

    private void nimTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nimTFFocusGained
        // TODO add your handling code here:
        if (nimTF.getText().equals("NIM")){
            nimTF.setText("");
            notifLabel.setText("");
        }
    }//GEN-LAST:event_nimTFFocusGained

    private void tglTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tglTFFocusGained
        // TODO add your handling code here:
        if (tglTF.getText().equals("Tanggal Lahir")){
            tglTF.setText("");
            notifLabel.setText("");
        }
    }//GEN-LAST:event_tglTFFocusGained

    private void tglTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tglTFFocusLost
        // TODO add your handling code here:
        if (tglTF.getText().equals("")){
            tglTF.setText("Tanggal Lahir");
            notifLabel.setText("");
        }
    }//GEN-LAST:event_tglTFFocusLost

    private void addUserBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserBTActionPerformed
        // TODO add your handling code here:
        mainSettingPanel.removeAll();
        mainSettingPanel.repaint();
        mainSettingPanel.revalidate();

        mainSettingPanel.add(addUserPanel);
        mainSettingPanel.repaint();
        mainSettingPanel.revalidate();
    }//GEN-LAST:event_addUserBTActionPerformed

    private void resetBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBTActionPerformed
        // TODO add your handling code here:
        new yesNo().setVisible(true);
    }//GEN-LAST:event_resetBTActionPerformed

    private void editCapilBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCapilBTActionPerformed
        // TODO add your handling code here:
        mainSettingPanel.removeAll();
        mainSettingPanel.repaint();
        mainSettingPanel.revalidate();

        mainSettingPanel.add(editCapilPanel);
        mainSettingPanel.repaint();
        mainSettingPanel.revalidate();
    }//GEN-LAST:event_editCapilBTActionPerformed

    private void nameCP1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameCP1FocusGained
        // TODO add your handling code here:
        if (nameCP1.getText().equals("Nama"))
            nameCP1.setText("");
    }//GEN-LAST:event_nameCP1FocusGained

    private void sourceCP1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sourceCP1FocusGained
        // TODO add your handling code here:
        if (sourceCP1.getText().equals("Source Image(location file)"))
            sourceCP1.setText("");
    }//GEN-LAST:event_sourceCP1FocusGained

    private void ketCP1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ketCP1FocusGained
        // TODO add your handling code here:
        if (ketCP1.getText().equals("Keterangan"))
            ketCP1.setText("");
    }//GEN-LAST:event_ketCP1FocusGained

    private void nameCP2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameCP2FocusGained
        // TODO add your handling code here:
        if (nameCP2.getText().equals("Nama"))
            nameCP2.setText("");
    }//GEN-LAST:event_nameCP2FocusGained

    private void sourceCP2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sourceCP2FocusGained
        // TODO add your handling code here:
        if (sourceCP2.getText().equals("Source Image(location file)"))
            sourceCP2.setText("");
    }//GEN-LAST:event_sourceCP2FocusGained

    private void ketCP2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ketCP2FocusGained
        // TODO add your handling code here:
        if (ketCP2.getText().equals("Keterangan"))
            ketCP2.setText("");
    }//GEN-LAST:event_ketCP2FocusGained

    private void nameCP1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameCP1FocusLost
        // TODO add your handling code here:
        if (nameCP1.getText().equals(""))
            nameCP1.setText("Nama");
    }//GEN-LAST:event_nameCP1FocusLost

    private void sourceCP1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sourceCP1FocusLost
        // TODO add your handling code here:
        if (sourceCP1.getText().equals(""))
            sourceCP1.setText("Source Image(location file)");
    }//GEN-LAST:event_sourceCP1FocusLost

    private void ketCP1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ketCP1FocusLost
        // TODO add your handling code here:
        if (ketCP1.getText().equals(""))
            ketCP1.setText("Keterangan");
    }//GEN-LAST:event_ketCP1FocusLost

    private void nameCP2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameCP2FocusLost
        // TODO add your handling code here:
        if (nameCP2.getText().equals(""))
            nameCP2.setText("Nama");
    }//GEN-LAST:event_nameCP2FocusLost

    private void sourceCP2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sourceCP2FocusLost
        // TODO add your handling code here:
        if (sourceCP2.getText().equals(""))
            sourceCP2.setText("Source Image(location file)");
    }//GEN-LAST:event_sourceCP2FocusLost

    private void ketCP2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ketCP2FocusLost
        // TODO add your handling code here:
        if (ketCP2.getText().equals(""))
            ketCP2.setText("Keterangan");
    }//GEN-LAST:event_ketCP2FocusLost

    private void submitCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitCPActionPerformed
        try {
            // TODO add your handling code here:
            dataCenter data = new dataCenter();
            data.readData();
            data.setCapil1(nameCP1.getText(), ketCP1.getText(), sourceCP1.getText());
            data.setCapil2(nameCP2.getText(), ketCP2.getText(), sourceCP2.getText());
            data.writeData();
            nameCP1.setText("");
            nameCP2.setText("");
            sourceCP1.setText("");
            sourceCP2.setText("");
            ketCP1.setText("");
            ketCP2.setText("");
        } catch (IOException ex) {
            Logger.getLogger(settingsPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submitCPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(settingsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(settingsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(settingsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(settingsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new settingsPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar Suara1;
    private javax.swing.JProgressBar Suara2;
    private javax.swing.JButton addUserBT;
    private javax.swing.JPanel addUserPanel;
    private javax.swing.JButton editCapilBT;
    private javax.swing.JPanel editCapilPanel;
    private javax.swing.JButton hasilBT;
    private javax.swing.JPanel hasilPanel;
    private javax.swing.JLabel headerHasil;
    private javax.swing.JLabel imgCapil1;
    private javax.swing.JLabel imgCapil2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea ketCP1;
    private javax.swing.JTextArea ketCP2;
    private javax.swing.JLabel labelCP1;
    private javax.swing.JLabel labelCP2;
    private javax.swing.JLabel logoSetting;
    private javax.swing.JButton logoutBT;
    private javax.swing.JPanel mainSettingPanel;
    private javax.swing.JPanel menuSettingPanel;
    private javax.swing.JTextField nameCP1;
    private javax.swing.JTextField nameCP2;
    private javax.swing.JLabel nimLabel;
    private javax.swing.JTextField nimTF;
    private javax.swing.JLabel notifLabel;
    private javax.swing.JButton resetBT;
    private javax.swing.JTextField sourceCP1;
    private javax.swing.JTextField sourceCP2;
    private javax.swing.JButton submitBT;
    private javax.swing.JButton submitCP;
    private javax.swing.JLabel tglLabel;
    private javax.swing.JTextField tglTF;
    private javax.swing.JLabel totCP1;
    private javax.swing.JLabel totCP2;
    private javax.swing.JLabel totSuara;
    // End of variables declaration//GEN-END:variables
}
